fl=ls('GLM_selec*.mat');
% features_tag={'sample selective during sample',...
%         'sample selective during early delay',...
%         'sample selective during late delay',...
%         'sample selective ONLY during late delay',...
%         'sample selective during decision making',...
%         'test selective during decision making',...
%         'pair selective during decision making',...
%         'pair selective ONLY during reward',...
%         'nonselective modulation during late delay',...
%         'nonselective modulation during decision making',...
%         'unmodulated'};


features_tag={'','Sample_SP',...
    'Sample_ED ',...
    'Sample_LD',...
    'Sample_LD*',...
    'Sample_DM',...
    'Test_DM',...
    'Pair_DM',...
    'Pair_RW',...
    'NSM_LD',...
    'NSM_DM',...
    'NON_MOD'};
    

for i=1:size(fl,1)
    disp(i)
    load(strtrim(fl(i,:)));
    fh=figure('Color','w','Position',[50,50,960,960]);
    subplot(2,2,1);
    [~,Iaic]=min(cell2mat(int_result(:,2)));
    mdl=int_result{Iaic,1};
    plot(mdl.Fitted{:,1},mdl.Variables{:,end},'r.','MarkerSize',10);
    text(min(xlim())+0.15*diff(xlim()),min(ylim())+0.85*diff(ylim()),sprintf('rsq = %.3f, p = %.3f',int_result{Iaic,3},int_result{Iaic,4}),'HorizontalAlignment','left')
    xlabel('GLM regression');
    ylabel('Experimental data')
    subplot(2,2,2);
    plot(cv_results(:,2),cv_results(:,1),'b.','MarkerSize',10);
    text(min(xlim())+0.15*diff(xlim()),min(ylim())+0.85*diff(ylim()),sprintf('rsq = %.3f, p = %.3f',r*r,p),'HorizontalAlignment','left')
    xlabel('Leave-one-region-out prediction');
    ylabel('Experimental data')
    
    
    uit=uitable(fh);
    uit.Data=table2array(mdl.Coefficients);
    uit.Position=[32,32,896,384];
    uit.ColumnName=mdl.Coefficients.Properties.VariableNames;
    if mdl.NumPredictors==4 && strcmp(int_result{Iaic,5},'interactions')
        RowNames={'Intercept',...
            sprintf('%s', features_tag{int_result{Iaic,6}(1)}),...
            sprintf('%s', features_tag{int_result{Iaic,6}(2)}),...
            sprintf('%s', features_tag{int_result{Iaic,6}(3)}),...
            sprintf('%s', features_tag{int_result{Iaic,6}(4)}),...
            sprintf('interact-%s-%s', features_tag{int_result{Iaic,6}(1)},features_tag{int_result{Iaic,6}(2)}),...
            sprintf('interact-%s-%s', features_tag{int_result{Iaic,6}(1)},features_tag{int_result{Iaic,6}(3)}),...
            sprintf('interact-%s-%s', features_tag{int_result{Iaic,6}(1)},features_tag{int_result{Iaic,6}(4)}),...
            sprintf('interact-%s-%s', features_tag{int_result{Iaic,6}(2)},features_tag{int_result{Iaic,6}(3)}),...
            sprintf('interact-%s-%s', features_tag{int_result{Iaic,6}(2)},features_tag{int_result{Iaic,6}(4)}),...
            sprintf('interact-%s-%s', features_tag{int_result{Iaic,6}(3)},features_tag{int_result{Iaic,6}(4)})};
    end
    
    uit.RowName=RowNames;
    uit.FontSize=12;
    uit.ColumnWidth={110,110,110,110};
    tiStr=num2str(i);
    if contains(fl(i,:),'vgat')
        tiStr=strcat(tiStr, 'VGAT');
    else
        tiStr=strcat(tiStr,'NPHR');
    end
    if contains(fl(i,:),'EFF')
        tiStr=strcat(tiStr, ' Effect Size');
    else
        tiStr=strcat(tiStr,' Opgen Selectivity');
    end
    
    
    tiStr=strcat(tiStr,'-ephys correlation-',regexp(fl(i,:),'(DM|ED|LD)-\w{2,8}','match'));
    sgtitle(tiStr)
    print([char(replace(tiStr,' ','_')),'.png'],'-dpng','-r150');
    close(fh)
end
